displayName: Test Only Requests
description: "This is an endpoint for testing the ttp service in different env - not to be used apart from debt transformation"
(annotations.sandboxData): !include ../../scenarios/view/getResponse.md
(annotations.scope): "read:time-to-pay-proxy"
securedBy: [ sec.x-application: { scopes: [ "read:time-to-pay-proxy" ] } ]
body:
  application/json:
    type: !include ../../schemas/test/requests.json
responses:
  200:
    body:
      text/plain:
        type: !include ../../schemas/test/requests.json
  400:
      body:
        text/plain:
          type: !include ../../schemas/errorRequestSchema.json
          example: !include ../../examples/badRequest.json
