displayName: Get Existing TTP Plan
description: "This is an endpoint that DAUI trigger a view a plan using ttp service"
(annotations.sandboxData): !include ../../scenarios/view/getResponse.md
(annotations.scope): "read:time-to-pay-proxy"
securedBy: [ sec.x-application: { scopes: [ "read:time-to-pay-proxy" ] } ]
body:
  application/json:
    type: !include ../../schemas/view/getViewRequestSchema.json
    examples:
      example-1:
        description: "A get request to view a plan"
        value: !include ../../examples/view/getViewRequest.json
responses:
  200:
    body:
      text/plain:
        type: !include ../../schemas/view/getViewResponseSchema.json
        example: !include ../../examples/view/getViewResponse.json
  400:
      body:
        text/plain:
          type: !include ../../schemas/errorRequestSchema.json
          example: !include ../../examples/badRequest.json
