displayName: Update Existing TTP Plan
description: "This is an endpoint that DAUI needs to update a TTP plan using ttp service"
(annotations.sandboxData): !include ../../scenarios/update/putResponse.md
(annotations.scope): "read:time-to-pay-proxy"
securedBy: [ sec.x-application: { scopes: [ "read:time-to-pay-proxy" ] } ]
body:
  application/json:
    type: !include ../../schemas/update/putUpdateRequestSchema.json
    examples:
      example-1:
        description: "A put request to update existing quote"
        value: !include ../../examples/update/putUpdateRequest.json
responses:
  200:
    body:
      text/plain:
        type: !include ../../schemas/update/putUpdateResponseSchema.json
        example: !include ../../examples/update/putUpdateReponse.json
  400:
      body:
        text/plain:
          type: !include ../../schemas/errorRequestSchema.json
          example: !include ../../examples/badRequest.json
