#%RAML 1.0
---
title: Time To Pay Proxy
description: This is a draft spec for the Time To Pay Proxy API.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/testing.md
 - title: Send fraud prevention data
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/fraud-prevention.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

'/individuals/time-to-pay-proxy':
  /quote:
    (annotations.group):
      name: Generate TTP Quote Request
      description: Debt Advisors using DAUI trigger a request to generate a draft quote.
    post: !include endpoints/generate/post.raml
  /quote/arrangement:
        (annotations.group):
          name: TTP Promote an Arrangement request
          description: DAUI triggers request to create a plan for storage
        post: !include endpoints/create/post.raml
  /quote/{customerReference}/{planId}:
        (annotations.group):
          name: Get Existing TTP Plan
          description: Debt Advisors using DAUI trigger a view and update a plan.
        get: !include endpoints/view/get.raml
        put: !include endpoints/update/put.raml
  /hello-world:
    get:
      displayName: Say hello world
      description: |
        An example for integrating with Time To Pay Proxy service.
        Any request to this endpoint initiates a 'Hello world' response.
      responses:
        200:
          body:
            text/html:
              example: |
                "Hello world"